version: '3.8'

services:
  # Firecrawl service - self-hosted web scraping API
  firecrawl:
    image: ghcr.io/mendableai/firecrawl:latest
    container_name: firecrawl-api
    ports:
      - "3002:3002"
    environment:
      - NODE_ENV=production
    volumes:
      - firecrawl_data:/app/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3002/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
